apiVersion: apps/v1
kind: Deployment
metadata:
  name: webervice1-deployment
  labels:
    app: webervice1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webervice1
  template:
    metadata:
      labels:
        app: webervice1
    spec:
      containers:
      - name: webervice1
        image: narenit/rishi:webserver1
        ports:
        - containerPort: 80
