apiVersion: v1
kind: Service
metadata:
  name: webervice2
  labels: 
    app: webervice2
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: webervice2

