apiVersion: v1
kind: Service
metadata:
  name: webervice1
  labels: 
    app: webervice1
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: webervice1

