apiVersion: v1
kind: Service
metadata:
  name: webervice3
  labels: 
    app: webervice3
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: webervice3

